[package]
name = "eots_constants"
version = "0.1.0"
edition = "2024"

[dependencies]
eots_skeleton_rig.workspace = true
perlin_noise.workspace = true
bevy.workspace = true
strum.workspace = true
strum_macros.workspace = true
