pub const CHUNK_SIZE: u32 = 16;
pub const CHUNK_SIZE_F32: f32 = CHUNK_SIZE as f32;
pub const CHUNK_SIZE_SQR: f32 = CHUNK_SIZE_F32 * CHUNK_SIZE_F32;
pub const HALF_CHUNK_SIZE_F32: f32 = CHUNK_SIZE_F32 * 0.5;

pub const VIEWER_DISTANCE_THRESHOLD: f32 = CHUNK_SIZE_F32 * 0.5;

pub const CHUNK_VIEW_RADIUS: i32 = 64 / CHUNK_SIZE as i32;
pub const CHUNK_VIEW_RADIUS_F32: f32 = CHUNK_VIEW_RADIUS as f32;
pub const CHUNK_VIEW_RADIUS_SQR: f32 = CHUNK_VIEW_RADIUS_F32 * CHUNK_VIEW_RADIUS_F32;
