[package]
name = "eots_core"
version = "0.1.0"
edition = "2024"

[dependencies]
eots_constants = { workspace = true }
rand = { workspace = true }
bevy = { workspace = true }
strum = { workspace = true }
